# Laboratorium 4 — NumPy zaawansowane
**Autor:** [Kacper Łapajski]


In [4]:
import numpy as np

Ćwiczenie 1: Broadcasting — zastosowania biznesowe


Krok 1 — Dane


In [5]:

# Ceny 4 produktów w 3 sklepach
ceny = np.array([[29.99, 31.99, 28.99], # Produkt A
[49.99, 52.99, 47.99], # Produkt B
[14.99, 15.99, 13.99], # Produkt C
[99.99, 104.99, 94.99]]) # Produkt D
sklepy = ['Centrum', 'Galeria', 'Online']
produkty = ['A', 'B', 'C', 'D']
print(f"Kształt macierzy: {ceny.shape}") # (4, 3)



Kształt macierzy: (4, 3)


Krok 2 — Zadania


Zadanie 1a: Stwórz nowy array z cenami podniesionymi o 5% (inflacja).
Wyświetl wynik.



In [10]:
ceny_po_inflacji = np.round(ceny * 1.05, 2)
print("Ceny po inflacji 5%:")
print(ceny_po_inflacji)

Ceny po inflacji 5%:
[[ 31.49  33.59  30.44]
 [ 52.49  55.64  50.39]
 [ 15.74  16.79  14.69]
 [104.99 110.24  99.74]]


Zadanie 1b: Stwórz array z cenami po rabacie. Każdy sklep daje inny rabat:
Centrum 10%, Galeria 5%, Online 15%

In [11]:
rabaty = np.array ([0.10, 0.05, 0.15])
ceny_po_rabacie = np.round(ceny * (1 - rabaty), 2)
print("Ceny po rabatach (Centrum 10%, Galeria 5%, Online 15%):")
print(ceny_po_rabacie)

Ceny po rabatach (Centrum 10%, Galeria 5%, Online 15%):
[[26.99 30.39 24.64]
 [44.99 50.34 40.79]
 [13.49 15.19 11.89]
 [89.99 99.74 80.74]]


Zadanie 1c: Oblicz koszt zakupu każdego produktu. Każdy produkt ma inną
marżę: A=30%, B=40%, C=25%, D=50%.

In [12]:
marza = np.array([[0.30], [0.40], [0.25], [0.50]])
koszt_zakupu = np.round(ceny / (1 + marza), 2)
print("Koszt zakupu każdego produktu:")
print(koszt_zakupu)

Koszt zakupu każdego produktu:
[[23.07 24.61 22.3 ]
 [35.71 37.85 34.28]
 [11.99 12.79 11.19]
 [66.66 69.99 63.33]]


Zadanie 1d: Wyświetl najtańszy sklep dla każdego produktu.

In [9]:
najtanszy_sklep = np.argmin(ceny, axis=1)
print("Najtańszy sklep dla każdego produktu:")
for i, produkt in enumerate(produkty):
    print(f"  Produkt {produkt}: {sklepy[najtanszy_sklep[i]]}")

Najtańszy sklep dla każdego produktu:
  Produkt A: Online
  Produkt B: Online
  Produkt C: Online
  Produkt D: Online


Ćwiczenie 2: Reshape i łączenie danych 

Zadanie 2a — Reshape

In [13]:
dane_flat = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])

kwartaly = dane_flat.reshape(4, 3)
print(f"Kwartały:\n{kwartaly}")
print(f"Suma per kwartał: {kwartaly.sum(axis=1)}")
print(f"Najlepszy kwartał: Q{kwartaly.sum(axis=1).argmax() + 1}")

Kwartały:
[[120 135  98]
 [142 167 189]
 [201 178 156]
 [143 198 221]]
Suma per kwartał: [353 498 535 562]
Najlepszy kwartał: Q4


Zadanie 2b


In [14]:
warszawa = np.array([150, 160, 170, 180])
krakow = np.array([120, 130, 140, 150])
wroclaw = np.array([90, 100, 110, 120])

wszystkie = np.vstack([warszawa, krakow, wroclaw])
print(f"Wszystkie:\n{wszystkie}")
print(f"Suma per oddział: {wszystkie.sum(axis=1)}")
print(f"Suma per kwartał: {wszystkie.sum(axis=0)}")

Wszystkie:
[[150 160 170 180]
 [120 130 140 150]
 [ 90 100 110 120]]
Suma per oddział: [660 540 420]
Suma per kwartał: [360 390 420 450]


Zadanie 2c:

In [15]:
sprzedaz_flat = np.array([100, 200, 150, 300, 250, 180, 120, 220, 170, 310, 260, 190])

# 1. Reshape na macierz 6×2
sprzedaz = sprzedaz_flat.reshape(6, 2)
print(f"Macierz sprzedaży:\n{sprzedaz}")

# 2. Średnia sprzedaż per produkt
srednia = np.round(sprzedaz.mean(axis=1), 2)
print(f"Średnia per produkt: {srednia}")

# 3. Zmiana między miesiącem 1 a 2
zmiana = sprzedaz[:, 1] - sprzedaz[:, 0]
print(f"Zmiana miesiąc 2 vs 1: {zmiana}")

Macierz sprzedaży:
[[100 200]
 [150 300]
 [250 180]
 [120 220]
 [170 310]
 [260 190]]
Średnia per produkt: [150. 225. 215. 170. 240. 225.]
Zmiana miesiąc 2 vs 1: [100 150 -70 100 140 -70]


Zadanie 2d:

In [16]:
# 1. Spłaszcz kwartały z zadania 2a
wektor = kwartaly.flatten()
print(f"Spłaszczony wektor: {wektor}")

# 2. Dodaj 13. miesiąc
wektor_13 = np.concatenate([wektor, np.array([235])])
print(f"Po dodaniu 13. miesiąca: {wektor_13}")
print(f"Liczba elementów: {len(wektor_13)}")

Spłaszczony wektor: [120 135  98 142 167 189 201 178 156 143 198 221]
Po dodaniu 13. miesiąca: [120 135  98 142 167 189 201 178 156 143 198 221 235]
Liczba elementów: 13


Ćwiczenie 3: Analiza danych finansowych

Dane

In [17]:

np.random.seed(2026)
# 8 pracowników, dane roczne
pracownicy = ['Anna', 'Jan', 'Ewa', 'Marek', 'Kasia', 'Piotr', 'Zofia', 'Tomek']
pensje = np.array([5500, 7200, 4800, 9100, 6300, 4200, 8500, 5800])
staz = np.array([3, 8, 2, 15, 5, 1, 12, 4])
oceny = np.array([4.2, 3.8, 4.5, 4.0, 4.7, 3.5, 4.3, 3.9])
# Sprzedaż miesięczna 4 produktów przez 6 miesięcy
produkty_nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Akcesorium']
sprzedaz = np.random.randint(20, 200, size=(4, 6))
ceny_produktow = np.array([3500, 1800, 2500, 150])


Zadanie 3a Analiza wynagrodzeń

In [18]:
nazwy = np.array(pracownicy)

srednia = pensje.mean()
mediana = np.median(pensje)
odch = np.round(pensje.std(), 2)

print(f"Średnia pensji: {srednia} zł")
print(f"Mediana pensji: {mediana} zł")
print(f"Odchylenie standardowe: {odch} zł")

print(f"\nPowyżej średniej: {nazwy[pensje > srednia]}")
print(f"Poniżej mediany: {nazwy[pensje < mediana]}")

rozstep = pensje.max() - pensje.min()
iqr = np.percentile(pensje, 75) - np.percentile(pensje, 25)
print(f"\nRozstęp: {rozstep} zł")
print(f"IQR: {iqr} zł")

Średnia pensji: 6425.0 zł
Mediana pensji: 6050.0 zł
Odchylenie standardowe: 1616.9 zł

Powyżej średniej: ['Jan' 'Marek' 'Zofia']
Poniżej mediany: ['Anna' 'Ewa' 'Piotr' 'Tomek']

Rozstęp: 4900 zł
IQR: 2200.0 zł


Zadanie 3b

In [19]:
premie = np.where(oceny >= 4.5, 2000, np.where(oceny >= 4.0, 1000, 0))
nowe_pensje = pensje + premie

print("Premie:")
for i in range(len(nazwy)):
    print(f"  {nazwy[i]}: {premie[i]} zł → łącznie {nowe_pensje[i]} zł")

najlepsza = nazwy[premie.argmax()]
print(f"\nNajwyższa premia: {najlepsza}")

Premie:
  Anna: 1000 zł → łącznie 6500 zł
  Jan: 0 zł → łącznie 7200 zł
  Ewa: 2000 zł → łącznie 6800 zł
  Marek: 1000 zł → łącznie 10100 zł
  Kasia: 2000 zł → łącznie 8300 zł
  Piotr: 0 zł → łącznie 4200 zł
  Zofia: 1000 zł → łącznie 9500 zł
  Tomek: 0 zł → łącznie 5800 zł

Najwyższa premia: Ewa


Zadanie 3c

In [20]:
kolejnosc = np.argsort(pensje)[::-1]

print("Ranking pracowników wg pensji:")
for i, idx in enumerate(kolejnosc, 1):
    print(f"  {i}. {nazwy[idx]} — {pensje[idx]} zł, staż: {staz[idx]} lat")

Ranking pracowników wg pensji:
  1. Marek — 9100 zł, staż: 15 lat
  2. Zofia — 8500 zł, staż: 12 lat
  3. Jan — 7200 zł, staż: 8 lat
  4. Kasia — 6300 zł, staż: 5 lat
  5. Tomek — 5800 zł, staż: 4 lat
  6. Anna — 5500 zł, staż: 3 lat
  7. Ewa — 4800 zł, staż: 2 lat
  8. Piotr — 4200 zł, staż: 1 lat


Zadanie 3d

In [21]:
kor_staz_pensja = np.corrcoef(staz, pensje)[0, 1]
kor_staz_ocena = np.corrcoef(staz, oceny)[0, 1]

print(f"Korelacja staż–pensja: {np.round(kor_staz_pensja, 3)}")
print(f"Korelacja staż–ocena:  {np.round(kor_staz_ocena, 3)}")

if abs(kor_staz_pensja) > abs(kor_staz_ocena):
    print("Silniejszy związek: staż–pensja")
else:
    print("Silniejszy związek: staż–ocena")

Korelacja staż–pensja: 0.988
Korelacja staż–ocena:  0.042
Silniejszy związek: staż–pensja


Zadanie 3e

In [22]:
ceny_kol = ceny_produktow.reshape(4, 1)
przychod = sprzedaz * ceny_kol

najlepszy_produkt = produkty_nazwy[przychod.sum(axis=1).argmax()]
najlepszy_miesiac = przychod.sum(axis=0).argmax() + 1

print(f"Najlepszy produkt: {najlepszy_produkt}")
print(f"Najlepszy miesiąc: M{najlepszy_miesiac}")

pierwsze_3 = przychod[:, :3].sum()
ostatnie_3 = przychod[:, 3:].sum()
print(f"\nPrzychód M1–M3: {pierwsze_3} zł")
print(f"Przychód M4–M6: {ostatnie_3} zł")
print(f"Trend: {'rosnący 📈' if ostatnie_3 > pierwsze_3 else 'malejący 📉'}")

Najlepszy produkt: Smartfon
Najlepszy miesiąc: M2

Przychód M1–M3: 2463950 zł
Przychód M4–M6: 2536500 zł
Trend: rosnący 📈


Ćwiczenie 4: Generowanie danych

Krok 1 — Generowanie danych:

In [23]:
np.random.seed(42)

wiek = np.clip(np.random.normal(35, 10, 100).astype(int), 18, None)
wydatki = np.clip(np.random.normal(500, 200, 100), 0, None)
wizyty = np.random.poisson(5, 100)

print("Dane wygenerowane!")
print(f"Liczba klientów: {len(wiek)}")

Dane wygenerowane!
Liczba klientów: 100


Krok 2 — Analiza:

In [24]:
# 1. Statystyki opisowe
for nazwa, dane in [('Wiek', wiek), ('Wydatki', wydatki), ('Wizyty', wizyty)]:
    print(f"{nazwa} — średnia: {dane.mean():.1f}, mediana: {np.median(dane):.1f}, "
          f"std: {dane.std():.1f}, min: {dane.min():.1f}, max: {dane.max():.1f}")

# 2. Korelacje
kor_wiek_wydatki = np.corrcoef(wiek, wydatki)[0, 1]
kor_wizyty_wydatki = np.corrcoef(wizyty, wydatki)[0, 1]
print(f"\nKorelacja wiek–wydatki:    {kor_wiek_wydatki:.3f}")
print(f"Korelacja wizyty–wydatki:  {kor_wizyty_wydatki:.3f}")

# 3. Segmentacja (np.select zamiast zagnieżdżonego where — jak sugeruje prowadzący)
sr = wydatki.mean()
sd = wydatki.std()

warunki = [wydatki > sr + sd, wydatki < sr - sd]
wartosci = ['WYSOKI', 'NISKI']
segment = np.select(warunki, wartosci, default='ŚREDNI')

# 4. Ile klientów w każdym segmencie
segmenty, liczby = np.unique(segment, return_counts=True)
print("\nSegmentacja klientów:")
for s, l in zip(segmenty, liczby):
    print(f"  {s}: {l} klientów ({l}%)")

# BONUS: np.diff — zmiana wydatków między kolejnymi klientami
roznice = np.diff(wydatki[:10])
print(f"\nZmiany wydatków (pierwsi 10 klientów): {np.round(roznice, 2)}")

Wiek — średnia: 33.6, mediana: 33.0, std: 8.6, min: 18.0, max: 53.0
Wydatki — średnia: 504.5, mediana: 516.8, std: 189.8, min: 116.2, max: 1044.0
Wizyty — średnia: 4.9, mediana: 5.0, std: 2.2, min: 1.0, max: 11.0

Korelacja wiek–wydatki:    -0.120
Korelacja wizyty–wydatki:  -0.159

Segmentacja klientów:
  NISKI: 17 klientów (17%)
  WYSOKI: 12 klientów (12%)
  ŚREDNI: 71 klientów (71%)

Zmiany wydatków (pierwsi 10 klientów): [ 198.95   15.59  -91.91  128.2   113.07  296.43 -342.32   16.59  -66.4 ]
