# Laboratorium 3 — NumPy
**Autor:** [Kacper]

In [55]:
import numpy as np

Krok 3


In [56]:
#1. Z listy
oceny = np.array([4.0, 3.5, 5.0, 4.5, 3.0, 4.0, 5.0])
print(f"Oceny: {oceny}")
print(f"Typ: {oceny.dtype}")

Oceny: [4.  3.5 5.  4.5 3.  4.  5. ]
Typ: float64


In [57]:
#2. Zera - 10 elementów
zera = np.zeros(10)
print(f"Zera: {zera}")

Zera: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [40]:
# 3. Jedynki — macierz 3×5
jedynki = np.ones((3, 5))
print(f"Jedynki:\n{jedynki}")

Jedynki:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [41]:
# 4. Sekwencja od 0 do 100, co 10
dziesiatki = np.arange(0, 101, 10)
print(f"Dziesiątki: {dziesiatki}")

Dziesiątki: [  0  10  20  30  40  50  60  70  80  90 100]


In [42]:
# 5. 7 równomiernych punktów od 0 do 1
ulamki = np.linspace(0, 1, 7)
print(f"Ulamki: {ulamki}")

Ulamki: [0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


In [43]:
# 6. 20 losowych ocen od 2 do 5
np.random.seed(42)
losowe_oceny = np.random.randint(2, 6, size=20)
print(f"Losowe oceny: {losowe_oceny}")


Losowe oceny: [4 5 2 4 4 5 2 2 4 3 4 4 4 4 5 2 5 5 5 4]


Krok 4

In [44]:
# Zbadaj tablicę losowych ocen
print(f"shape: {losowe_oceny.shape}")
print(f"ndim:{losowe_oceny.ndim}")
print(f"size: {losowe_oceny.size}")
print(f"dtype: {losowe_oceny.dtype}")


shape: (20,)
ndim:1
size: 20
dtype: int32


Ćwiczenie 2


Część A

In [45]:
miesiące_sprzedaz = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])
# Indeksy: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11
# Miesiące:Sty Lut Mar Kwi Maj Cze Lip Sie Wrz Paź Lis Gru
# 1. Sprzedaż w styczniu (indeks 0)
print(f"Sprzedaż w styczniu: {miesiące_sprzedaz[0]}")
#2. Sprzedaż w grudniu (ostatni element):
print(f"Sprzedaż w grudniu: {miesiące_sprzedaz[-1]}")
#3. Sprzedaż w Q1 (styczeń-marzec, indeksy 0-2):
print(f"Sprzedaż w Q1: {miesiące_sprzedaz[0:3]}")
#4. Sprzedaż w Q4 (październik-grudzień, ostatnie 3):
print(f"Sprzedaż w Q4: {miesiące_sprzedaz[-3:]}")
#5. Sprzedaż co drugi miesiąc (styczeń, marzec, maj…):
print(f"Sprzedaż co drugi miesiąc: {miesiące_sprzedaz[::2]}")
#6. Sprzedaż od tyłu (grudzień → styczeń):
print(f"Sprzedaż od tyłu: {miesiące_sprzedaz[::-1]}")

Sprzedaż w styczniu: 120
Sprzedaż w grudniu: 221
Sprzedaż w Q1: [120 135  98]
Sprzedaż w Q4: [143 198 221]
Sprzedaż co drugi miesiąc: [120  98 167 201 156 198]
Sprzedaż od tyłu: [221 198 143 156 178 201 189 167 142  98 135 120]


Część B

In [46]:
# Sprzedaż 4 produktów w 3 kwartałach
dane = np.array([
    [120, 145, 167],    # Produkt A
    [89, 102, 95],   # Produkt B
    [234, 267, 289], # Produkt C
    [56, 78, 91]     # Produkt D
])
produkty = ['Produkt A', 'Produkt B', 'Produkt C', 'Produkt D']
kwartały = ['Q1', 'Q2', 'Q3']            

Zadania

1. Sprzedaż Produktu A w Q2 (wiersz 0, kolumna 1):


In [47]:
print(f"Sprzedaż Produktu A w Q2: {dane[0, 1]}")

Sprzedaż Produktu A w Q2: 145


2. Cała sprzedaż Produktu C (wiersz 2, wszystkie kolumny):


In [48]:
print(f"Sprzedaż Produktu B: {dane[1,:]}")

Sprzedaż Produktu B: [ 89 102  95]


3. Sprzedaż wszystkich produktów w Q1 (wszystkie wiersze, kolumna 0):


In [49]:
print(f"Sprzedaż w Q1: {dane[:, 0]}")

Sprzedaż w Q1: [120  89 234  56]


4. Sprzedaż Produktów B i C w Q2 i Q3 (wiersze 1-2, kolumny 1-2):

In [50]:
print(f"Sprzedaż Prduktu B i C w Q2 i Q3:\n{dane[1:3, 1:3]}")

Sprzedaż Prduktu B i C w Q2 i Q3:
[[102  95]
 [267 289]]


Ćwiczenie 3


In [51]:
#Dane
# Produkty w sklepie internetowym
nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Słuchawki', 'Ładowarka',
'Klawiatura', 'Mysz', 'Monitor', 'Kamera', 'Drukarka']
ceny = np.array([3499, 1899, 2499, 349, 89, 249, 129, 1499, 599, 899])
ilosci_magazyn = np.array([15, 42, 78, 156, 312, 89, 201, 23, 45, 34])
oceny_klientow = np.array([4.7, 4.2, 4.5, 4.8, 3.9, 4.1, 4.3, 4.6, 3.8, 3.5])

Zadanie 1: Podstawowe statystyki cenowe

In [52]:
print(f"Średnia cena: {ceny.mean():.2f} PLN")
print(f"Najdoroższy produkt: {nazwy[ceny.argmax()]} za {ceny.max()} PLN")
print(f"Najatańszy produkt: {nazwy[ceny.argmin()]} za {ceny.min()} PLN")

Średnia cena: 1171.00 PLN
Najdoroższy produkt: Laptop za 3499 PLN
Najatańszy produkt: Ładowarka za 89 PLN


Zadanie 2: Wartość magazynu


In [53]:
cena_produktu = ceny * ilosci_magazyn 
for nazwa, wartosc in zip(nazwy, cena_produktu):
    print(f"Wartość produktu {nazwa}: {wartosc:.2f} PLN")

print(f"\nWartość magazynu: {np.sum(ceny * ilosci_magazyn):.2f} PLN")

Wartość produktu Laptop: 52485.00 PLN
Wartość produktu Tablet: 79758.00 PLN
Wartość produktu Smartfon: 194922.00 PLN
Wartość produktu Słuchawki: 54444.00 PLN
Wartość produktu Ładowarka: 27768.00 PLN
Wartość produktu Klawiatura: 22161.00 PLN
Wartość produktu Mysz: 25929.00 PLN
Wartość produktu Monitor: 34477.00 PLN
Wartość produktu Kamera: 26955.00 PLN
Wartość produktu Drukarka: 30566.00 PLN

Wartość magazynu: 549465.00 PLN


Zadanie 3: Analiza cenowa

In [54]:
promocja_swiateczna = ceny * 0.85
ceny_z_vat = ceny * 1.23

print("Promocja_swiateczna:")
print(promocja_swiateczna)

print("Ceny_z_vat:")
print(ceny_z_vat)

print("\nPromocja świąteczna (15% zniżki):")
for nazwa, wartosc in zip(nazwy, promocja_swiateczna):
    print(f"Cena produktu {nazwa} po promocji: {wartosc:.2f} PLN")

print("\nCena z VAT (23%):")
for nazwa, wartosc in zip(nazwy, ceny_z_vat):
    print(f"Cena produktu {nazwa} z VAT: {wartosc:.2f} PLN")

powyzej_1000 = (ceny > 1000).sum()
print(f"\nLiczba produktów powyżej 1000 zł: {powyzej_1000}")

Promocja_swiateczna:
[2974.15 1614.15 2124.15  296.65   75.65  211.65  109.65 1274.15  509.15
  764.15]
Ceny_z_vat:
[4303.77 2335.77 3073.77  429.27  109.47  306.27  158.67 1843.77  736.77
 1105.77]

Promocja świąteczna (15% zniżki):
Cena produktu Laptop po promocji: 2974.15 PLN
Cena produktu Tablet po promocji: 1614.15 PLN
Cena produktu Smartfon po promocji: 2124.15 PLN
Cena produktu Słuchawki po promocji: 296.65 PLN
Cena produktu Ładowarka po promocji: 75.65 PLN
Cena produktu Klawiatura po promocji: 211.65 PLN
Cena produktu Mysz po promocji: 109.65 PLN
Cena produktu Monitor po promocji: 1274.15 PLN
Cena produktu Kamera po promocji: 509.15 PLN
Cena produktu Drukarka po promocji: 764.15 PLN

Cena z VAT (23%):
Cena produktu Laptop z VAT: 4303.77 PLN
Cena produktu Tablet z VAT: 2335.77 PLN
Cena produktu Smartfon z VAT: 3073.77 PLN
Cena produktu Słuchawki z VAT: 429.27 PLN
Cena produktu Ładowarka z VAT: 109.47 PLN
Cena produktu Klawiatura z VAT: 306.27 PLN
Cena produktu Mysz z VAT: 158.67

Zadanie 4: Filtrowanie

In [70]:
nazwy_array = np.array(nazwy)

maska_ocena = oceny_klientow >= 4.5
print("Produkty z oceną >= 4.5:")
for nazwa, cena in zip(nazwy_array[maska_ocena], ceny[maska_ocena]):
    print(f"Produkt: {nazwa}, Cena: {cena} PLN")

Produkty z oceną >= 4.5:
Produkt: Laptop, Cena: 3499 PLN
Produkt: Smartfon, Cena: 2499 PLN
Produkt: Słuchawki, Cena: 349 PLN
Produkt: Monitor, Cena: 1499 PLN


In [71]:
maska_cena = ceny < 200
print("\nProdukty poniżej 200 zł:")
for nazwa, ilosc in zip(nazwy_array[maska_cena], ilosci_magazyn[maska_cena]):
    print(f"Produkt: {nazwa}, Ilość w magazynie: {ilosc} szt.")


Produkty poniżej 200 zł:
Produkt: Ładowarka, Ilość w magazynie: 312 szt.
Produkt: Mysz, Ilość w magazynie: 201 szt.


Zadanie 5: Analiza zapasów

In [77]:
nazwy_array = np.array(nazwy)

maska_niski_stan = ilosci_magazyn < 30
print("Produkty z niskim stanem magazynowym (< 30 szt.):")
for nazwa, ilosc in zip(nazwy_array[maska_niski_stan], ilosci_magazyn[maska_niski_stan]):
    print(f"  {nazwa}: {ilosc} szt.")

wartosci = ceny * ilosci_magazyn
wartosc_niski_stan = wartosci[maska_niski_stan].sum()
print(f"\nŁączna wartość tych produktów: {wartosc_niski_stan:.2f} PLN")

wartosc_calego_magazynu = wartosci.sum()
procent = (wartosc_niski_stan / wartosc_calego_magazynu) * 100
print(f"Stanowią {procent:.2f}% wartości całego magazynu")

Produkty z niskim stanem magazynowym (< 30 szt.):
  Laptop: 15 szt.
  Monitor: 23 szt.

Łączna wartość tych produktów: 86962.00 PLN
Stanowią 15.83% wartości całego magazynu


Zadanie 6 (bonus): Analiza korelacji cena–ocena


In [78]:
nazwy_array = np.array(nazwy)
maska_okazja = (oceny_klientow >= 4.5) & (ceny < 1000)
print("Okazje (ocena >= 4.5 i cena < 1000 zł):")
for nazwa, cena in zip(nazwy_array[maska_okazja], ceny[maska_okazja]):
    print(f" {nazwa}: {cena} PLN")

maska_dobra_ocena = oceny_klientow >= 4.0
srednia_dobra = ceny[maska_dobra_ocena].mean()
srednia_slaba = ceny[~maska_dobra_ocena].mean()
print(f"\nŚrednia cena produktów z dobrą oceną >= 4.0: {srednia_dobra:.2f} PLN")
print(f"Średnia cena produktów z słabą oceną < 4.0: {srednia_slaba:.2f} PLN")

Okazje (ocena >= 4.5 i cena < 1000 zł):
 Słuchawki: 349 PLN

Średnia cena produktów z dobrą oceną >= 4.0: 1446.14 PLN
Średnia cena produktów z słabą oceną < 4.0: 529.00 PLN


Ćwiczenie 4: Benchmark — lista vs NumPy

Benchmark

In [79]:
import time

In [80]:
rozmiar = 1_000_000
lista = list(range(rozmiar))
tablica = np.array(lista)


# Test 1

In [81]:
start=time.perf_counter()
wynik_lista = [x * 2 for x in lista]
czas_lista = time.perf_counter() - start

start = time.perf_counter()
wynik_numpy = tablica * 2
czas_numpy = time.perf_counter() - start

print(f"=== Mnożenie * 2 ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")


=== Mnożenie * 2 (1,000,000 elementów) ===
Lista: 99.7 ms
NumPy: 3.5 ms
NumPy jest 29× szybszy!


# Test 2

In [82]:
start = time.perf_counter()
suma_lista = sum(lista)
czas_lista = time.perf_counter() - start
start = time.perf_counter()
suma_numpy = tablica.sum()
czas_numpy = time.perf_counter() - start
print(f"\n=== Suma ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")



=== Suma (1,000,000 elementów) ===
Lista: 8.2 ms
NumPy: 1.6 ms
NumPy jest 5× szybszy!


# Test 3

In [83]:
start = time.perf_counter()
filtr_lista = [x for x in lista if x > 500000]
czas_lista = time.perf_counter() - start
start = time.perf_counter()
filtr_numpy = tablica[tablica > 500000]
czas_numpy = time.perf_counter() - start
print(f"\n=== Filtrowanie > 500k ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")


=== Filtrowanie > 500k (1,000,000 elementów) ===
Lista: 65.3 ms
NumPy: 2.7 ms
NumPy jest 25× szybszy!


## Wnioski z benchmarku

- NumPy jest **29x** szybszy w mnożeniu
- NumPy jest **5x** szybszy w sumowaniu
- NumPy jest **25** szybszy w filtrowaniu
- Wniosek: przy dużych danych **zawsze** używaj NumPy zamiast list